# Generated by Django 4.1 on 2024-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_contact_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
