# Generated by Django 4.1 on 2024-06-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
